version: "3"
services:
  mongodb:
    image: mongo
    container_name: great_api_mongo_db
    ports:
      - "55432:27017"
    volumes:
      - ./mongodb/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root_user
      - MONGO_INITDB_ROOT_PASSWORD=root_pass